# Copyright 2025 KrakLabs
# SPDX-License-Identifier: AGPL-3.0-or-later

# GoReleaser Configuration
# GoReleaser configuration for CIE releases
#
# Test:    goreleaser check
# Build:   goreleaser build --snapshot --clean
# Release: goreleaser release (runs via GitHub Actions)
# Docs:    https://goreleaser.com/customization/

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

# ==============================================================================
# Project Settings
# ==============================================================================
project_name: cie

# ==============================================================================
# Before Hooks
# ==============================================================================
before:
  hooks:
    - go mod tidy
    - go generate ./...

# ==============================================================================
# Build Configuration
# ==============================================================================
builds:
  - id: cie
    main: ./cmd/cie
    binary: cie
    env:
      - CGO_ENABLED=1
    # CGO cross-compilation requires native toolchains for each target
    # For v0.1.0, we build only for Linux amd64 (the CI runner's native platform)
    # macOS builds require running on macOS runners
    # Future: use matrix builds with partial releases
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

# ==============================================================================
# Archives
# ==============================================================================
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

# ==============================================================================
# Checksums
# ==============================================================================
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# ==============================================================================
# Snapshot (for testing)
# ==============================================================================
snapshot:
  version_template: "{{ incpatch .Version }}-dev"

# ==============================================================================
# Changelog
# ==============================================================================
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other"
      order: 999

# ==============================================================================
# Release
# ==============================================================================
release:
  github:
    owner: kraklabs
    name: cie
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## CIE {{ .Tag }}

    Code Intelligence Engine - semantic search and call graph analysis for your codebase.

    ### Installation

    **Homebrew (macOS/Linux):**
    ```bash
    brew install kraklabs/cie
    ```

    **Go Install:**
    ```bash
    go install github.com/kraklabs/cie/cmd/cie@{{ .Tag }}
    ```

    **Download Binary:**
    Download the appropriate archive for your platform below.

  footer: |
    ---
    **Full Changelog**: https://github.com/kraklabs/cie/compare/{{ .PreviousTag }}...{{ .Tag }}

# ==============================================================================
# Homebrew Tap (disabled until HOMEBREW_TAP_TOKEN secret is configured)
# ==============================================================================
# brews:
#   - name: cie
#     repository:
#       owner: kraklabs
#       name: homebrew-tap
#       branch: main
#       token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
#     directory: Formula
#     homepage: "https://github.com/kraklabs/cie"
#     description: "Code Intelligence Engine - semantic search and call graph analysis"
#     license: "AGPL-3.0-or-later"
#     skip_upload: auto
#     test: |
#       system "#{bin}/cie", "--version"
#     install: |
#       bin.install "cie"

# ==============================================================================
# Announce (optional)
# ==============================================================================
# announce:
#   skip: true